
K1_TOOLCHAIN_DIR=/usr/local/k1tools

IMAGE=memcpy
SRC=main
# DEBUG=-DDEBUG
DEBUG=

$(IMAGE).mpk: src/$(SRC).c
	mkdir -p bin/
	k1-gcc -Wall -DMPPA=1 -mos=rtems $(DEBUG) src/$(SRC).c  -o $(SRC) -lmppaipc
	rm -f bin/$(IMAGE).mpk
	createImage.rb --boot=$(SRC) -T bin/$(IMAGE).mpk	
	rm -f $(SRC) $(BIN_SLAVE)

clean:
	rm -f *~ $(SRC) bin/$(IMAGE).mpk
